- name: build
  task: rollup -c rollup.config.js

- name: format
  tasks: 
    - prettier --write 'bin/**/*.{mjs,js}'
    - prettier --write '*.{js,json}'

- name: test/spec
  task: nyc ava

- name: coverage
  tasks:
    - taskfile test/spec
    - - nyc report --reporter=text-lcov | coveralls

- name: test
  task: taskfile test/spec
