- name: format
  tasks:
      - prettier --write '{bin,src}/**/*.{mjs,js}'
      - prettier --write '*.{mjs,js,json,yml}'

- name: coverage
  tasks:
      - taskfile test
      - - nyc report --reporter=text-lcov | coveralls

- name: test
  tasks:
      - eslint "{bin,src}/**/**.{mjs,js}"
      - - prettier --list-different '{bin,src}/**/*.{mjs,js}'
      - - prettier --list-different '*.{mjs,js,json,yml}'
      - - - readlint
      - - - - nyc ava
